microhh/microhh

- README.md
- cases/drycblles/drycbllesstats.py
- config/macbook.cmake
- config/macbook_brew.cmake
- config/macbook_brew_gcc.cmake
- config/macbook_clang.cmake
Hi Chiel,
we met two/three times at MPI-HH. I visited a couple of times from BTU Cottbus and worked on the UCLA-LES.
I re-familiarize myself with CUDA and am looking into MicroHH as a real world example. I made two changes to it to make the drycblles example work as in the README. First, I changes the paths to libcufft so MicroHH compiles on a Mac with CUDA enabled. Second, I used 'th' instead of 's' in the plotting script, since 's' is not present in the netCDF file and is plotted as theta anyway.
--
Eckhard
> Running the dry boundary layer example case

- include/advec.h
- include/advec_2.h
- include/advec_2i4.h
- include/advec_2i5.h
- include/advec_2i53.h
- include/advec_2i62.h
- include/advec_4.h
- include/advec_4m.h
- include/advec_disabled.h
- src/advec_2.cxx
- src/advec_2i4.cxx
- src/advec_2i5.cxx
- src/advec_2i53.cxx
- src/advec_2i62.cxx
- src/advec_4.cxx
- src/advec_4m.cxx
- src/advec_disabled.cxx
- src/stats.cxx
The old `get_advec_flux` operated on the absolute fields (like in advection itself), not on the turbulent quantities. This gives strange values for the conditionally averaged statistics. This fix subtracts the mask averaged mean profiles from `w` and the statistics field itself, such that the fluxes calculated in `get_advec_flux` are `<w^prime x fld^prime>` instead of `<w x fld>`.
> Fix flux statistics

- src/advec_2i53.cu
`get_advec_flux` is purely a statistics function, and should have never been defined in the CUDA advection code.
Tests:
- code compiles again on the CPU and GPU.
- `drycblles` with `2i53` advection on CPU works.
- `drycblles` with `2i53` advection on GPU throws "not implemented error".
> Fixed CUDA compilation

- CMakeLists.txt
- main/CMakeLists.txt
- src/CMakeLists.txt
@thijsheus Please have a look, if I use `target_include_directories` as now seems the standard, it all works well.
> Make CMake fixes to let generic work on mac as well.

- include/thermo_buoy.h
- include/thermo_disabled.h
- include/thermo_dry.h
- include/thermo_vapor.h
- src/cross.cxx
- src/microphys.cxx
- src/radiation.cxx
- src/radiation_disabled.cxx
- src/radiation_rrtmgp.cxx
- src/timeloop.cxx
The main change is a bugfix in our date/time bookkeeping; the problem is that `strptime(..., &tm_struct)` leaves a number of variables in `tm_struct` undefined, which could cause a +/- 0/1 hour offset on random MPI tasks. I'm not entirely sure why this worked correctly before: on some systems, it seems that at least `tm_gmtoff` was the same on all MPI tasks... This fix explicitly initializes all variables left undefined by `strptime()`.
The other commits are simply missing includes, and an update of the RRTMGP submodule.
> Date/time bugfix, missing includes, and submodule version

- src/model.cxx
`post` mode does not work correctly on the GPU. Since nearly all statistics are anyhow calculated on the CPU, it does not really make sense to run `post` mode on the GPU. Therefore, I suggest to just throw an error when `post` and CUDA are combined.
> Don't allow `post` mode on the GPU.

- src/advec_2.cxx
- src/stats.cxx
Fixed the stat flux bug at the surface for advec_2; it seems like a buffer overflow read at the surface and the top; we may have gotten lucky for the no-mask situation. I couldn't quickly judge whether this issue plays for other advection schemes as well.
> Issue 109 - Stat flux bug

- src/field3d_io.cxx
- src/grid_parallel.cxx
- src/grid_serial.cxx
- src/thermo_moist.cxx
- src/timeloop.cxx
The main part of the code now seems to be warning free again.
> Declaring several fread statements as (void) to get rid of warnings

- src/stats.cxx
- src/thermo_moist.cxx
While testing for BOMEX, two hard coded  thl/qt_bot in thermo moist fell out. There may be more; we'll find them in the testing all cases.
> Making multiple stat vars declarations an error.

- include/land_surface_kernels_gpu.h
- src/boundary_surface_lsm.cu
At least the land-surface is leak free now, but MicroHH overall isn't. `compute-sanitizer` is also reporting leaks of the nudge `timedep` profiles (only those, the others `timedep`'s from force are not leaking), but I can't find the error there. The `timedep->clear_device()` functions are called for those `timedep`'s at the end of the simulation.
> `cudaFree`'ed the land-surface model.

- include/microphys_disabled.h
- src/force.cxx
- src/timedep.cxx
Bugfix timedep nudging; there was a nested loop, where for each item in `nudgelist`, all items in `tdep_nudge` were created. Additionally adds a missing include in `microphys_disabled.h`.
> Timedep nudge fix; no more leaks!

- include/background_profs.h
- include/stats.h
- src/model.cxx
- src/stats.cxx
The number of era_levels is no longer hard coded in stat, but pulled from background_prof instead
> Pulling # of background levels in stat from background

- python/microhh_tools.py
Fixes https://github.com/microhh/microhh/issues/129
Copy the radiation, lsm, and aerosol files to the run dir using the microhh_tools.
> microhh_tools copying of auxilary files

- src/boundary_surface_bulk.cu
It's a combination that we never use in any of our cases, but a bug nonetheless...
> Missing `if()` in `boundary_surface_bulk`.

- include/microphys_disabled.h
- src/microphys_disabled.cxx
IMHO this is the least ugly solution; creating an entire `microphys_fixed_Nc0_Ni0` (...) class only to return two constants seems a bit overkill. I made `Nc0` and `Ni0` optional in `microphys_disabled` (defaulting to `-1`), but if they are requested and not initialized, an error is thrown.
> Allow disabled microphys to return `Nc0` and `Ni0` for LES with

- src/boundary_surface_bulk.cxx
- src/fields.cxx
- src/stats.cxx
This is a first attempt at fixing the buffer overflow in the stats. I've put the bounds inside the calc_mean() function to kstart/kend, so that every caller has to decide on its own what the bounds are supposed to be.
At first glance (tested with RICO), this implementation does not seem to throw valgrind warnings, and I didn't see any NaNs in the netcdf file either. Better testing is still necessary, and help is appreciated.
> Valgrind stats

- src/force.cxx
- src/grid.cxx
- src/radiation_gcss.cxx
- src/radiation_rrtmgp.cxx
- src/radiation_rrtmgp_rt.cu
- src/radiation_rrtmgp_rt.cxx
This commit makes lat/lon a requirement if it is necessary in force or radiation. It also leaves it out of stats if it is not given in the namelist.
> Require lat lon

- config/generic.cmake
Prerparing code for a wider range of GPUs in generic.cmake, so that it should run on most current GPUs out of the box.
> Generic cmake cuda

- .gitmodules
- CMakeLists.txt
One option to git rid of `clang-tidy`:
- Made a fork of `kernel_launcher` in the MicroHH organisation;
- On the `kernel_launcher` side, compilation/CMake defaults to using `clang-tidy`;
- On the MicroHH side the default is the opposite: unless `-DUSECLANGTIDY=true` is set, `clang-tidy` is disabled.
> Disable `clang-tidy` in Kernel Launcher by default.

- python/3d_to_nc.py
- python/microhh_tools.py
- src/radiation_gcss.cxx
Such checks should happen in the caller functions. This already was fixed in cross through the addition of grid location in the filename; in dump/restart files this is now done with a (short) list of half level vars in 3d_to_nc
> Remove check on half levels in microhh_tools

- cases/drycblles/drycblles.ini
- cases/drycblles/drycblles_stats.py
- src/stats.cxx
This is the first batch of fixes to the flux stats. This solves the Moser180 problem, but not the `2i5` flux problem. There is a wiggle in the profile near, which disappears if one resets the `fld_prime->fld_mean` to `0`. This suggests that there is a problem with the mean, which is hard to understand. I need help :).
> Flux stats bug

- python/microhh_tools.py
I had accidentally pushed this into Barts branch; putting it here as a separate PR for clarity. Depending on merging order, it may become obsolete.
> Fixing #204 trailing spaces in mhh_tools namelist reader

- include/diff_kernels.h
- include/diff_smag2_kl_kernels.cuh
- src/diff_smag2.cxx
- src/diff_tke2.cxx
It seems that the error related to the wall-resolved LES has been solved, and was the result of one erroneous template parameter value in `diff_smag2.cxx`. I have a working Moser180 on CPU and GPU.
Also I have marked all if statements depending on `surface_model` as `constexpr` to ensure compile time evaluation.
> Resolved wall LES working on CPU and GPU

- python/microhh_tools.py
- src/radiation_rrtmgp_rt.cu
in cabauw_rt.ini.base, under [cross], xy is given for multiple levels. This is read as a list of integers, which causes line 155 of 'microhh_tools.py'  to crash when trying to save the namelist, because ','.join(list) does not work for a list of integers. Converting any list of non-strings to a list of strings fixes this problem
> Update to work with the latest version of the raytracing + ensure only lists of strings are saved in the namelist 

- src/boundary_surface_bulk.cu
`boundary_surface_bulk` tried to `cudaFree` some `cuda_vector`'s, which caused RICO on the GPU to fail.
> Don't `cudaFree` the `cuda_vector`'s.

- cases/cabauw/cabauw.ini.base
- cases/cabauw/cabauw_input.py
- include/background_profs.h
- include/radiation_rrtmgp.h
- include/radiation_rrtmgp_rt.h
- src/aerosol.cxx
- src/background_profs.cxx
- src/radiation_rrtmgp.cxx
- src/radiation_rrtmgp_rt.cxx
As discussed, some name changes in the code/ini file/Cabauw case:
- Renamed `swupdatecolumn` to `swtimedep_column`
- Put both the aerosol and T/h2o/... background at the same NetCDF `time_rad` dimension.
For testing, I added the option for time dependent background/aerosol profiles to the Cabauw case. In addition, I made the simulation period a bit more flexible, by explicitly setting the `start_date` and `end_date` in `cabauw_input.py`. As a test, I ran the case twice, once from 09-11 UTC, and once from 10-11 UTC. In both cases, the aerosol/background profiles are identical at 10 and 11 UTC:
> Aerosol/background naming changes + update `cabauw` case.

- src/radiation_rrtmgp.cu
- src/radiation_rrtmgp_rt.cu
Fixes GPU compilation. Tested with Cabauw case, with `use_aerosols=True/False`, `use_tdep_aerosols=True/False`, `use_tdep_gasses=True/False` and `use_tdep_background=True/False`.
> Fixed incorrect names aerosol and timedep switches.

- include/thermo_moist_functions.h
I found an inconsistency in our `qsat_liq()` and `dqsatdT_liq()` calculations. Comparing `dqsatdT_liq()` and `dqsatdT_ice()`, there are some `+` and `-` switched:
`Ice: return (ep<TF>/den + (TF(1.) - ep<TF>)*ep<TF>*esat_ice(T)/pow2(den)) * Ls<TF>*esat_ice(T) / (Rv<TF>*pow2(T));`
`Liq: return (ep<TF>/den - (TF(1.) + ep<TF>)*ep<TF>*esat_liq(T)/pow2(den)) * Lv<TF>*esat_liq(T) / (Rv<TF>*pow2(T));`
I compared our `dqsatdT_liq()` function (blue line) with `dqsatdT` diagnosed as `(qsat[T+dT] - qsat[T]) / dT` (black), and our version deviates at higher temperatures.
The green line contains the fix from this PR, which also isn't exact, as the function still assumes that `Lv` is not temperature dependent. If I quickly (just for testing) add `Lv(T)`, the result is closer to the diagnosed `dqsatdT` …
> Fixed +/- bug in `dqsatdT` calculation.

- cases/cabauw/cabauw_input.py
- src/fields.cxx
- src/stats.cxx
The surface mask was not applied to the 2D statistics. Fixes https://github.com/microhh/microhh/issues/258
Discussion point: the routine `calc_stats_2d()` is only used for surface fields, and as such, now uses the surface mask. Should we rename this function to e.g. `calc_stats_surface()`? In principle, you could throw a 2D xy slice from a 3D field in this function, but then the incorrect mask would be used.
Old results:
New results:
> Bugfix masked surface statistics.

- src/model.cxx
In the current code, the restart state is saved on a thread, to allow the model to continue. We did make a copy of the background state for stats, but did not solve the problem for a standard save. I did not like the copy solution for stats for the general code, because the copy is only made for the GPU. On the CPU it works because the threading is disabled. This solution does the save of thermo on the main thread.
With this fix we are good to go for 2.0!
> Save thermo state before splitting off the thread to avoid overwrite and failing restarts

- src/budget.cxx
This makes the documentation consistent, and makes the switch behave as other on/off switches in the code.
> Change the sw_budget switch to boolean, to make it uniform to other switches

- src/timeloop.cxx
Prevent the code for running with a time step of exactly 0
> Check idt, but also the value of the limiter idtlim being 0.

- src/model.cxx
- src/stats.cxx
Potential fix for https://github.com/microhh/microhh/issues/265.
Not sure where we can best print the statistics message, since stats is split into the `some_process->exec_stats()` and the `stats->exec()` parts, with cross-sections and dumps in between.
> Print cross/dump messages before actually triggering the functions.

- src/boundary_surface_lsm.cxx
Few extra land-surface crosses. Mostly `G` and `S`, I also added `H` and `LE`, although you could easily calculate those from `thl_fluxbot` and `qt_fluxbot`.
> Added land-surface crosses for `G` + `S` (with `H` + `LE` as bonus).

- src/thermo_dry.cxx
`drycblles` + column stats segfaults on the CPU, because of a missing base state copy, similar to the one in `thermo_dry->exec_stats()` or `thermo_moist->exec_column()`.
No need to wrap the copy in `#ifndef USECUDA`, since that is already outside of `thermo_dry->exec_column()`
> `exec_column` in `thermo_dry` was missing a base state copy.

- CMakeLists.txt
- README.md
Every new user runs into our Git submodule trap. This PR checks if one of the submodules is initialized, and if not, shows instructions on how to init them.
bart@eddy:~/tmp/microhh/build_dp_cpu$ cmake -DSYST=ubuntu_20lts ..
-- Precision: Double (64-bits floats)
-- The CXX compiler identification is GNU 9.4.0
-- The Fortran compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- MPI: Disabled.
-- CUDA: Disabled.
-- Build Type: RELEASE
-- Compiler …
> Check submodules with CMake

- config/snellius.cmake
These modules are listen too often = maintenance nightmare. Instead, just link to the documentation.
> Removed old modules from Snellius cmake config.

- cases/dispersion/dispersion_base.ini
- cases/dispersion/dispersion_input.py
- src/source.cxx
Kept it simple; `line_x` et al. are optional now, and default to an empty list. If not specified in the .ini, these vectors are resized to the size of `source_x`, and filled with zeros.
Tested with the `dispersion` case, which no longer specifies `list_xyz` (previously these were set to `0,0`).
[source][line_x]              =  EMPTY LIST   (default)
[source][line_y]              =  EMPTY LIST   (default)
[source][line_z]              =  EMPTY LIST   (default)
> Make `line_xyz` in `source` optional, and default to list with zeros.

- include/diff_tke2_kl_kernels.cuh
- src/diff_tke2.cu
- src/diff_tke2.cxx
A few small performance tweaks, helps to speed up `diff2_tke` kernels in `double` mode. Can directly be merged into `develop` as well.
> Include constexpr, and merge sqrt division for performance.
