microhh/microhh

CMakeLists.txt
cases/rcemip/link_coefficients.py
config/archlinux.cmake
config/generic.cmake
config/macbook_brew.cmake
config/macbook_brew_gcc.cmake
config/snellius.cmake
config/ubuntu.cmake
config/ubuntu_20lts.cmake
include/radiation_rrtmgp.h
include/radiation_rrtmgp_functions.h
src/CMakeLists.txt
src/radiation_rrtmgp.cu
src/radiation_rrtmgp.cxx

This is the new radiation code. RCEMIP works fine, all other things need thorough checking, but it would be good to merge this ASAP.

Main new rad

---

config/archlinux.cmake

Tested on an up-to-date Manjaro system.

Update Arch/Manjaro config file.

---

cases/cabauw/cabauw_rt_input.py
include/radiation.h
include/radiation_disabled.h
include/radiation_gcss.h
include/radiation_prescribed.h
include/radiation_rrtmgp.h
include/radiation_rrtmgp_rt.h
src/radiation_rrtmgp.cu
src/radiation_rrtmgp.cxx
src/radiation_rrtmgp_rt.cu
src/radiation_rrtmgp_rt.cxx

This is the first PR that will come on this topic. I had to make a lot of changes to the radiation, and would prefer to merge this first, before building the link to the surface scheme. I have tested the standard and RT radiation on CPU and GPU and got good results. This PR also fixes a bug in the aerosol stats, which triggered an exception if swstats was off, because there was no switch around.

Implementation of radiation using 2D and band dependent albedo and emissivity

---

src/radiation_rrtmgp_rt.cxx

Lat/lon in rrtmgp_rt was read from radiation instead of using the values

Rrtmgp rt latlon

---

cases/bomex/bomex.ini
include/dump.h
include/model.h
python/3d_to_nc.py
python/microhh_tools.py
src/dump.cxx
src/model.cxx
src/radiation_gcss.cxx

This is useful for detailed  calculatations, such as entrainment/detrainment calculations following Dawe and Austin

Performing 2 dumps on consecutive time steps

---

src/force.cu

Implementation of momentum subsidence on the GPU. BOMEX runs.

Momentum Subsidence on GPU

---

cases/arm/arm_stats.py
cases/bomex/bomex_stats.py
cases/dycoms/dycoms_stats.py

The python files to create statistics are now working again for BOMEX; added for ARM and DYCOMS

Fix case stats

---

cases/weisman_klemp/weisman_klemp.ini
cases/weisman_klemp/weisman_klemp_input.py

Fixes incorrect p_bot because of using top of domain values to calculate surface variables and pressure in final step.

use surface theta instead of top of domain at k=-1

---

python/cross_to_nc.py
python/microhh_tools.py

The script now runs again. Fixes https://github.com/microhh/microhh/issues/147
No changes in chunking yet

Fixing cross-section-to-netcdf script

---

python/3d_to_nc.py
python/cross_to_nc.py
python/microhh_tools.py

Fixes https://github.com/microhh/microhh/issues/152

Optimizations to the cross and dump python scripts

---

cases/cabauw/cabauw.ini.base
src/radiation_rrtmgp.cxx

The implementation on the CPU was only finished ~half, and never tested......

Radiation homogenization was never implemented on the CPU, so throw

---

cases/bomex/bomex.ini
cases/bomex/bomex_stats.py
include/fields.h
src/budget.cxx
src/budget_2.cxx
src/budget_4.cxx
src/fields.cxx

Resolves issues https://github.com/microhh/microhh/issues/165 and https://github.com/microhh/microhh/issues/145

Move TKE stats to fields; budget order equal to spatial order

---

src/boundary_surface_bulk.cxx
src/fields.cxx

Fixes https://github.com/microhh/microhh/issues/171 and a conditional flag error in boundary_bulk

Fixing two valgrind errors

---

src/netcdf_interface.cxx

Fixes https://github.com/microhh/microhh/issues/181
Some spots in the netcdf_interface had try/catch blocks; others did not, leading to simple "NetCDF Errors" for the users, without much clarification what needed to be done.

Try/catch blocks around all netcdf::get_variable functions

---

src/cross.cxx
src/thermo_dry.cxx

Fix some LnGrad cross-section mistakes

---

python/cross_to_nc.py

Write values for unlimited variables in cross_to_nc

---

src/boundary.cxx

`grad_bot` was not set when using `sbot_2d_list`. For LES this is okay, for DNS not.

Also set `grad_bot` in case of DNS with spatial `sbot`.

---

cases/drycblles/drycblles.ini
cases/drycblles/drycblles_stats.py
include/advec.h
include/advec_2.h
include/advec_2i4.h
include/advec_2i5.h
include/advec_2i62.h
include/advec_4.h
include/advec_4m.h
include/advec_disabled.h
src/advec_2.cxx
src/advec_2i4.cxx
src/advec_2i5.cxx
src/advec_2i62.cxx
src/advec_4.cxx
src/advec_4m.cxx
src/advec_disabled.cxx
src/stats.cxx

To solve https://github.com/microhh/microhh/pull/202

Main flux bug fix

---

include/radiation_rrtmgp.h
src/radiation_rrtmgp.cu

fixes a problem that occurred when saving statistics for individual columns in simulations on gpu with aerosols.

Fix column stats

---

include/source.h
include/source_kernels.h
src/source.cu
src/source.cxx

Apologies for the late addition to RC1, but time dependent sources was the last option which was not yet implemented on the GPU.
Both time dependent time and locations now work, comparison with the CPU version shows that the GPU implementation (here with both a varying location and time) works:
https://github.com/microhh/microhh/assets/1067637/b395e394-4ae4-4324-8591-e8363c122931

Ported time dependent source location/strength to the GPU.

---

cases/cabauw/cabauw_input.py
cases/cabauw/cabauw_test.py
python/microhh_tools.py
src/force.cxx

Fixes issue #246.
Also Fixes a few issues with the cabauw case (although it still crashes for me).

Nudgefac_exception

---

cases/cabauw/cabauw.ini.base
cases/cabauw/cabauw_input.py
src/radiation_rrtmgp.cxx
src/radiation_rrtmgp_rt.cu
src/radiation_rrtmgp_rt.cxx

Plus bugfix ray-tracer column stats. I don't think those ever worked, since the CPU pointer was passed...
Fixes https://github.com/microhh/microhh/issues/244

Fixes to allow column stats without normals stats.

---

CONTRIBUTORS.md
README.md

Of course after the release, but nonetheless good to fix.

Updated Readme and Contributors.

---

README.md

Simplified text a bit, and added a vimeo link.

Updated README.md text.

---

.github/workflows/develop.yml
.gitignore
README.md
cases/run_ci_tests.py

This compiles the code in SP + CP + CPU + CPUMPI, and runs a small set of tests. Should work for both pushes (tested) and PRs (not tested) on `develop`.

First setup Github actions

---

cases/arm/arm_test.py
cases/cabauw/cabauw.ini.base
cases/cabauw/cabauw_input.py
cases/cabauw/cabauw_restart_test.py
cases/run_restart_set.py
include/radiation_rrtmgp.h
include/thermo.h
include/thermo_buoy.h
include/thermo_disabled.h
include/thermo_dry.h
include/thermo_moist.h
src/boundary_surface_lsm.cxx
src/model.cxx
src/radiation_rrtmgp.cu
src/radiation_rrtmgp.cxx
src/thermo_moist.cxx

A few fixes to get bitwise identical restart files with radiation, land-surface, etc. Fixes non-identical restart files with:
- Time varying `p_bot`. For simplicity, I now dump the entire base state to a restart file, instead of only saving a part and re-computing the rest in the `run` phase.
- Time varying basestate when using radiation. If pressure varies, the background radiation always has to be recomputed.
- Heterogeneous z0's in the land-surface model. Since the iterative Obukhov length solver starts from the previous Obukhov length, these need to be stored for each tile, instead of only saving the "bulk" Obukhov length.
There is a new `cabauw_restart_test.py` scripts that test a selection of all the permutations that are possible in the Cabauw case. Most pass now, except for runs …

Bitwise identical restarts for `cabauw` case.

---

python/cross_to_nc.py

As discussed in issue: https://github.com/microhh/microhh/issues/291
Fixes https://github.com/microhh/microhh/issues/291

Fixed time issue in cross script.

---

src/radiation_gcss.cu
src/radiation_gcss.cxx

Consistent GCSS radiation implementation between cpu and gpu.

---

include/thermo.h
include/thermo_buoy.h
include/thermo_disabled.h
include/thermo_dry.h
include/thermo_moist.h
include/thermo_moist_functions.h
python/microhh_tools.py
src/model.cxx
src/thermo_dry.cxx
src/thermo_moist.cu
src/thermo_moist.cxx

Draft, ARM still crashes, and can't find the bug.

BOMEX bug.

---

src/radiation_rrtmgp.cu
src/radiation_rrtmgp.cxx
src/radiation_rrtmgp_rt.cu

Fixes https://github.com/microhh/microhh/issues/280

Bugfix combination LSM without SW or LW radiation.

---

cases/conservation/conservation_funcs.py
cases/conservation/conservation_test.py
cases/dycoms/dycoms.ini
cases/rcemip/rcemip_input.py
cases/run_all.py
cases/run_restart_set.py
cases/run_small_set.py
cases/taylorgreen/taylorgreen_test.py
python/microhh_tools.py

Ensuring that all runscripts run with the correct paths. Run_all, run_restart, run_ci, run_small now all pass.

Fix runscripts

---

include/fields.h
python/microhh_tools.py
src/fields.cxx
src/model.cxx
src/thermo_dry.cxx
src/thermo_moist.cxx

All tests (CI + restart) passing.

Write base state `rho` to its own restart file.
